# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ngMdok4JqUEGnQznu3BdYBsq-Jl58EbZ
"""

import random

def getRandom():
 return random.uniform(0, 1)



def calc(n,l,v,r):
  g=1
  t=0
  while t < n:
    if g<=0:
      return 0

    if getRandom()<v:
      g=(g+r*l*g)
      t+=1
    else:
      g=(g-g*l)
      t+=1
  return g

def globalcalc(k):
  return -calc(4000,k)

def printCounter(n,l,v,r):
  arr=[]
  for i in range(1,1001):
    arr.append(round(calc(n,l,v,r)))
  from collections import Counter
  import matplotlib.pylab as plt

  lists = sorted(Counter(arr).items()) # sorted by key, return a list of tuples

  x, y = zip(*lists) # unpack a list of pairs into two tuples

  plt.plot(x, y)
  plt.show()
  plt.xlabel(str(n)+" "+str(l)+" "+str(v)+" "+str(r))
  print(Counter(arr))

import numpy
print(numpy.arange(0.5,0.7,0.02))
for i in range(0,15):
 printCounter(7000,0.01,numpy.arange(0.5,0.7,0.2/15)[i],0.7)

import numpy
print(numpy.arange(0.5,0.7,0.02))
for i in range(0,15):
 printCounter(7000,0.01,numpy.arange(0.5,0.7,0.2/15)[i],0.8)